on: 
  schedule:
  - cron: 0 0 * * *
name: Daily Collection
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: NPM Build
      run: npm install
    - name: Collect Go Metrics 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node cli.js repo-search go --output=logs
    - name: Collect JS Metrics 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node cli.js repo-search javascript --output=logs
    - name: Collect Google Trends 
      run: node cli.js trends --output=logs
    - name: Re-write README
      run: node cli.js readme
    - name: Publish Logs to Repo
      uses: mikeal/publish-to-github-action@master
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
